//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reserva
    {
        public int reserva_Id { get; set; }

        [Display(Name = "Nome do Hóspede")]
        public string hospede { get; set; }
        [Display(Name = "Data de Nascimento")]
        public string data_nascimento1 { get; set; }
        [Display(Name = "Cpf")]
        public string cpf1 { get; set; }
        [Display(Name = "Sexo")]
        public bool sexo { get; set; }
        [Display(Name = "Data da Reserva")]
        public System.DateTime data_reserva { get; set; }
        [Display(Name = "Data de Saída")]
        public System.DateTime data_saida { get; set; }
        [Display(Name = "Hora de Entrada")]
        public System.TimeSpan horario_entrada { get; set; }
        [Display(Name = "Hora de Saída")]
        public System.TimeSpan horario_saida { get; set; }
        [Display(Name = "Tipo de Reserva")]
        public string tipo_reserva { get; set; }
        [Display(Name = "Tipo de Acomodação")]
        public string quarto { get; set; }
        [Display(Name = "Número do Quarto")]
        public short num_quarto { get; set; }
        [Display(Name = "Status de Relacionamento")]
        public string status_relacionamento1 { get; set; }
        [Display(Name = "Telefone")]
        public short telefone1 { get; set; }
        [Display(Name = "Email")]
        public string email1 { get; set; }
    }
}
